# Generated by Django 4.2.25 on 2025-10-23 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(blank=True, help_text='Used to auto-fill details', max_length=13, null=True)),
                ('description', models.TextField(blank=True)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('GOD', 'Good'), ('FAR', 'Fair'), ('DMG', 'Damaged')], default='NEW', max_length=3)),
                ('status', models.CharField(choices=[('AVL', 'Available'), ('PND', 'Pending Exchange'), ('EXC', 'Exchanged')], default='AVL', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listed_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PND', 'Pending'), ('ACC', 'Accepted'), ('REJ', 'Rejected'), ('CMP', 'Completed')], default='PND', max_length=3)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to='exchange.book')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_exchanges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('book', 'requester')},
            },
        ),
    ]
