# Generated by Django 4.2.25 on 2025-10-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchange',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='exchange',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PND', 'ACC'])), fields=('book', 'requester'), name='unique_pending_or_accepted_exchange'),
        ),
    ]
