# Generated by Django 4.2.25 on 2025-10-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_alter_exchange_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='delivered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='exchanged',
            field=models.BooleanField(default=False),
        ),
    ]
