# Generated by Django 4.2.25 on 2025-10-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_book_delivered_book_exchanged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='updated_at',
        ),
    ]
